const redirects = [
    { from: '/browse/shows/10-things-scare-me', to: '/browse/shows/10-things-that-scare-me' },
    { from: '/browse/shows/dopequeens', to: '/browse/shows/2-dope-queens' },
    { from: '/browse/shows/atc', to: '/browse/shows/all-things-considered' },
    { from: '/browse/shows/bl', to: '/browse/shows/brian-lehrer-show' },
    { from: '/browse/shows/the-brian-lehrer-show', to: '/browse/shows/brian-lehrer-show' },
    { from: '/browse/shows/bl-daily-politics-podcast', to: '/browse/shows/brian-lehrer-a-daily-politics-podcast' },
    { from: '/browse/shows/the-latest-episodes-from-caught', to: '/browse/shows/caught' },
    { from: '/browse/shows/documentaryweek', to: '/browse/shows/documentary-of-the-week' },
    { from: '/browse/shows/experiment', to: '/browse/shows/the-experiment-wnyc' },
    { from: '/browse/shows/fishko', to: '/browse/shows/fishko-files' },
    { from: '/browse/shows/freshair', to: '/browse/shows/fresh-air' },
    { from: '/browse/shows/fresh-air-with-terry-gross', to: '/browse/shows/fresh-air' },
    { from: '/browse/shows/latenight', to: '/browse/shows/late-night-whenever' },
    { from: '/browse/shows/lies', to: '/browse/shows/lies-wnyc' },
    { from: '/browse/shows/radiolabmoreperfect', to: '/browse/shows/more-perfect' },
    { from: '/browse/shows/me', to: '/browse/shows/morning-edition' },
    { from: '/browse/shows/newsounds', to: '/browse/shows/new-sounds' },
    { from: '/browse/shows/tnyradiohour', to: '/browse/shows/new-yorker-radio-hour' },
    { from: '/browse/shows/notetoself', to: '/browse/shows/note-to-self' },
    { from: '/browse/shows/anxiety', to: '/browse/shows/notes-from-america' },
    { from: '/browse/shows/otm', to: '/browse/shows/on-the-media' },
    { from: '/browse/shows/onlyhuman', to: '/browse/shows/only-human' },
    { from: '/browse/shows/classical-music-happy-hour', to: '/browse/shows/our-common-nature' },
    { from: '/browse/shows/our-common-nature-podcast', to: '/browse/shows/our-common-nature' },
    { from: '/browse/shows/pieceofwork', to: '/browse/shows/a-piece-of-work' },
    { from: '/browse/shows/theseason', to: '/browse/shows/the-season' },
    { from: '/browse/shows/whiteguys', to: '/browse/shows/sooo-many-white-guys' },
    { from: '/browse/shows/stonewall-fifty', to: '/browse/shows/the-sound-of-pride-stonewall-at-50' },
    { from: '/browse/shows/takeaway', to: '/browse/shows/the-takeaway' },
    { from: '/browse/shows/ted', to: '/browse/shows/ted-radio-hour' },
    { from: '/browse/shows/radiolab-kids', to: '/browse/shows/terrestrials' },
    { from: '/browse/shows/neighborhood', to: '/browse/shows/there-goes-the-neighborhood' },
    { from: '/browse/shows/fleas', to: '/browse/shows/this-podcast-has-fleas' },
    { from: '/browse/shows/trumpinc', to: '/browse/shows/trump-inc' },
    { from: '/browse/shows/universe-art', to: '/browse/shows/universe-of-art' },
    { from: '/browse/shows/the-moth', to: 'https://themoth.org/' },
    { from: '/browse/shows/moth-radio-hour', to: 'https://themoth.org/' },
    { from: '/browse/shows/moth', to: 'https://themoth.org/' },
    { from: '/browse/shows/world', to: 'https://theworld.org/' },
    { from: '/browse/shows/throughline', to: 'https://www.npr.org/podcasts/510333/throughline' },
    { from: '/browse/shows/american-life', to: 'https://www.thisamericanlife.org/' },
    { from: '/browse/shows/splendid-table', to: 'https://www.splendidtable.org/' },
    { from: '/browse/shows/spooked', to: 'https://spookedpodcast.org/' },
    { from: '/browse/shows/snapjudgment', to: 'https://snapjudgment.org/' },
    { from: '/browse/shows/shorts', to: 'https://www.symphonyspace.org/selected-shorts/episodes/unexpected-guests' },
    { from: '/browse/shows/reveal', to: 'https://revealnews.org/' },
    { from: '/browse/shows/q', to: 'https://www.cbc.ca/arts/q' },
    { from: '/browse/shows/pulse', to: 'https://whyy.org/programs/the-pulse/' },
    { from: '/browse/shows/planet-money', to: 'https://www.npr.org/sections/money/127413729/planet-money/' },
    { from: '/browse/shows/news-hour', to: 'https://www.pbs.org/newshour/' },
    { from: '/browse/shows/iqus2', to: 'https://opentodebate.org/' },
    { from: '/browse/shows/marketplace', to: 'https://www.marketplace.org/' },
    { from: '/browse/shows/left-right-and-center', to: 'https://www.kcrw.com/shows/left-right-center/all-episodes' },
    { from: '/browse/shows/le-show', to: 'https://www.wwno.org/le-show' },
    { from: '/browse/shows/latino-usa', to: 'https://www.latinousa.org/' },
    { from: '/browse/shows/jazz-loft', to: 'https://www.wnyc.org/' },
    { from: '/browse/shows/hypothesis', to: 'https://hypothesispodcast.podbean.com/' },
    { from: '/browse/shows/freakonomics-radio', to: 'https://freakonomics.com/' },
    { from: '/browse/shows/how-i-built-this', to: 'https://wondery.com/shows/how-i-built-this/?_branch_match_id=1428821510339979692&utm_source=npr&utm_medium=web&_branch_referrer=H4sIAAAAAAAAA8soKSkottLXL8%2FPS0ktqtRLLCjQy8nMy9aPtHAprSzwLbXIS7KvK0pNSy0qysxLj08qyi8vTi2ydc4oys9NBQCwvcy7PgAAAA%3D%3D' },
    { from: '/browse/shows/new-york-capitol-press-room', to: 'https://capitolpressroom.org/' },
    { from: '/browse/shows/capitol-connection', to: 'https://www.wamc.org/show/the-capitol-connection' },
    { from: '/browse/shows/bullseye', to: 'https://www.npr.org/podcasts/510309/bullseye' },
    { from: '/browse/shows/bbc-world-service', to: 'https://www.bbc.com/audio/play/live/bbc_world_service' },
    { from: '/browse/shows/bbc-newshour', to: 'https://www.bbc.com/audio/brand/p002vsnk' },
]

export default defineEventHandler((event) => {
    // Cache for 24 hours (86400 seconds) in the client's browser/app
    setResponseHeader(event, 'Cache-Control', 'public, max-age=86400, stale-while-revalidate=3600')
    return redirects
})