# fly.toml app configuration file generated for radiolab-vue

app = "wnyc-vue3"
primary_region = "iad"

[env]
  PORT = "8080"
  TZ = "America/New_York"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[http_service.http_options]
  idle_timeout = 900

[http_service.http_options]
  idle_timeout = 1800

[[http_service.checks]]
  interval = "30s"
  grace_period = "10s"
  method = "GET"
  path = "/"
  protocol = "http"
  timeout = "15s"
  tls_skip_verify = false

[http_service.concurrency]
  type = "connections"
  hard_limit = 25
  soft_limit = 20

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
