# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  before_all do
    setup_circle_ci
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end


  lane :beta do
    begin
      # Adjust the `build_type` and `flavor` params as needed to build the right APK for your setup
      gradle(
        task: 'assemble', 
        build_type: 'Release'
      )
      upload_to_play_store(
        release_status: 'draft',
        package_name: 'org.wnyc.android'
      ) # upload to Google Play Store
      slack(
        channel: "#releases",
        message: "New WNYC Build uploaded to Google Play Store :tada:",
        default_payloads: [:lane, :test_result],
        success: true
      )
    rescue => exception
      on_error(exception)
    end
  end
  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  def on_error(exception)
    slack(
        message: "Lane failed with exception : #{exception}",
        success: false
    )
  end
end
