source "https://rubygems.org"

gem 'cocoapods', '>= 1.16.0'
gem 'fastlane'
gem "abbrev" # Required for Ruby 3.4+

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
